# Generated by Django 5.1.3 on 2024-11-30 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed'), ('Canceled', 'Canceled')], max_length=20)),
                ('payment_method', models.CharField(choices=[('M-Pesa', 'M-Pesa'), ('CreditCard', 'CreditCard')], max_length=50)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('response_code', models.CharField(max_length=10)),
                ('response_description', models.CharField(max_length=255)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.order')),
            ],
        ),
    ]
